"""initial migrations - adding categories table

Revision ID: b40ea786ec23
Revises: 
Create Date: 2021-07-26 15:23:43.199130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40ea786ec23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blog', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'contact', ['id'])
    op.create_unique_constraint(None, 'notification', ['id'])
    op.create_unique_constraint(None, 'plan', ['id'])
    op.create_unique_constraint(None, 'subcategory', ['id'])
    op.create_unique_constraint(None, 'task', ['id'])
    op.drop_column('task', '_categories')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('task', sa.Column('_categories', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_constraint(None, 'subcategory', type_='unique')
    op.drop_constraint(None, 'plan', type_='unique')
    op.drop_constraint(None, 'notification', type_='unique')
    op.drop_constraint(None, 'contact', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'blog', type_='unique')
    # ### end Alembic commands ###
