"""empty message

Revision ID: d840521c9cc9
Revises: 023cdaad2518
Create Date: 2021-08-23 09:41:42.735818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd840521c9cc9'
down_revision = '023cdaad2518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'website')
    op.drop_column('task', 'facebook')
    op.drop_column('task', 'bio')
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'bio')
    op.add_column('task', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('facebook', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
